# Docker Compose configuration for production environment

version: '3.8'

services:
  storefront-agent:
    build: .
    container_name: storefront-agent-prod
    environment:
      - ENVIRONMENT=production
    env_file:
      - env.production
    volumes:
      - ./logs:/app/logs
    networks:
      - storefront-network
    restart: always
    command: ["python", "-m", "storefront_agent.cli", "run", "--environment", "production"]
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'

  # MCP Server for production
  mcp-server:
    image: your-mcp-server:production
    container_name: mcp-server-prod
    ports:
      - "8080:8080"
    environment:
      - MCP_ENVIRONMENT=production
    networks:
      - storefront-network
    restart: always
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.25'
        reservations:
          memory: 256M
          cpus: '0.1'

networks:
  storefront-network:
    driver: bridge
